### ISSUE TITLE
TAAR v.3 add-on is wrongly installed and functional on profiles out of the 2 to 30 days lifespan

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/taar#100] opened 2018-06-26 17:35 UTC
[Affected versions]:
- Firefox Beta 61.0b2

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a new Firefox profile with the latest version of the "TAAR v3" add-on installed (downloaded from https://bugzilla.mozilla.org/show_bug.cgi?id=1469546).
- Create the following prefs in the "about:config" page:
"shieldStudy.logLevel" as string and set it to "All";
"extensions.taarexpv3_shield_mozilla_org.test.variationName" as string and set it to "control", "intervention-a" or "intervention-b"

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to three websites and observe the behavior.

[Expected result]:
- The TAAR pop-up is not triggered.

[Actual result]:
- The TAAR pop-up is triggered.

[Notes]:
- This is also reproducible with profiles older than 30 days.
- Attached a screen recording of the issue:

![fresh profile](https://user-images.githubusercontent.com/26000308/41929314-57ca64f4-7980-11e8-99aa-6d8c5655b9d1.gif)

**Comment by crankycoder** [comment] 2018-07-17 16:42
cc/ @motin

**Comment by motin** [comment] 2018-07-18 09:11
Looks like an incorrectly filed duplicate of https://github.com/motin/taar-experiment-v3-shield-study/issues/36 - please close

**Closed** 2018-07-18 09:13 UTC
