### ISSUE TITLE
The "TAAR v3" shield study wrongly works on an ineligible Firefox build

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/taar#99] opened 2018-06-26 13:58 UTC
Also logged in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1471216
***
**[Affected versions]:**
- Firefox Beta (61.0) locales other than en-Us, en-GB, de, fr, ru, pt-BR, es-ES, pl, it, ar, ja.

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "TAAR v3" add-on (downloaded from https://bugzilla.mozilla.org/show_bug.cgi?id=1469546) installed.
- Create the following prefs in the "about:config" page:
	- "shieldStudy.logLevel" as string and set it to "All";
	- "extensions.taarexpv3_shield_mozilla_org.test.variationName" as string and set it to "control", "intervention-a" or "intervention-b"

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to three websites and observe the behavior.

**[Expected result]:**
- The websites are correctly opened.

**[Actual result]:**
- A "File not found" doorhanger is opened on the third website.

**[Notes]:**
- Also, the shield study's pings are displayed in the Browser Console and on the "about:telemetry" page.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41917041-20c780f4-7962-11e8-8bb9-9c65ac229cf3.gif)

**Comment by crankycoder** [comment] 2018-07-17 16:41
cc/ @motin

**Comment by motin** [comment] 2018-07-18 09:11
Looks like an incorrectly filed duplicate of https://github.com/motin/taar-experiment-v3-shield-study/issues/27 - please close

**Closed** 2018-07-18 09:13 UTC
